name:
             - '♡さくら♡'
             - 'あけみ♡卍'
answer_words:
             - 'マジ!?'
             - 'ヤバたん😂'
             - 'すきぴ💓😘'
             - '(;_;)'
             - 'あざまる水産🐟'

open_greets:
             - 'おっは〜😍'
             - 'PON⭐PON!!'

end_greets:
             - 'ジャネバイっ✡'
             - 'おつ〜'
             - 'おつぽよ〜'
             - 'またタピろ❤(ӦｖӦ｡)'
